version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: simple_cms
    volumes:
      - .:/usr/src/app
    #env_file:
    #  - .env/development/database
    #  - .env/development/web
  database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: simple_cms
    #env_file:
    #  - .env/development/database
    volumes:
      - db_data:/var/lib/postgresql/simple_cms
volumes:
  db_data: